version: '3.8'

services:
  auth-service:
    build:
      context: ./src/apps/auth
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src/apps/auth:/app
    environment:
      - PYTHONUNBUFFERED=1
      - ROOT_PATH=/auth  # Важно для корректной работы FastAPI
    working_dir: /app
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - auth-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge